### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by leoTiGRiS** [MarkKoz/ReactBot#1]
drops me a syntaxerror 
![image](https://user-images.githubusercontent.com/44180995/55553490-030c0980-56e9-11e9-98ef-8f5dc1be058a.png)

**Comment by MarkKoz** [comment]
What does `python --version` show? As stated in the readme, the version must be at least 3.6.

**Comment by leoTiGRiS** [comment]
> What does `python --version` show? As stated in the readme, the version must be at least 3.6.

![image](https://user-images.githubusercontent.com/44180995/55553696-91808b00-56e9-11e9-8df2-cdb6855ce9e7.png)
Oh so my version is 2.7..

**Comment by leoTiGRiS** [comment]
I updated python but it still shows me the same version. What should I do?

**Comment by MarkKoz** [comment]
Try uninstalling Python 2 before installing Python 3. In the Python 3 installer, make sure you select the option to add Python to environment variables. Lastly, be sure to use a new command prompt window after installing Python 3.

I'm closing this issue because I intend for issues to be used for reporting issues with the program, not with your environment. I wont be providing any more basic Python support here; there are surely plenty of answers online elsewhere anyway. If you find a problem with the program, feel free to open a new issue.
